### ISSUE TITLE
Error in usage example

### ISSUE THREAD

**Issue by Dagur** [apa512/clj-rethinkdb#122]
I tried copying and pasting the usage example but I get this error:
```
Exception in thread "main" clojure.lang.ExceptionInfo: Index `genre` was not found on table `test.authors`. {:t 18, :e 4100000, :r ["Index `genre` was not found on table `test.authors`."], :b []}, compiling:(C:\Users\Dagur\IdeaProjects\dagurbiz\src\dagurbiz\core.clj:12:1)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$script_opt.invoke(main.clj:337)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
It seems that the index-create function is failing silently

**Comment by Dagur** [comment]
It seems that the server just needs a little time to create the index before I use it. If I run this in the repl I don't get any errors.
