### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by anthonygalea** [apa512/clj-rethinkdb#145]
In an attempt to measure test coverage I ran `lein cloverage` on the project and got:

```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot find resource rethinkdb/response.clj, compiling:(/private/var/folders/lz/pbkqvmr96676yfkqdpzvq5mrgysf_z/T/form-init3964204768538778710.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
```

**Comment by danielcompton** [comment]
Looks like cloverage needs to be updated to support cljc files.

**Comment by anthonygalea** [comment]
Yep: https://github.com/lshift/cloverage/pull/93
I'll get back to this when/if cloverage adds support for cljc files.
Thanks.
